apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: lessons12-monitor
  labels:
    app: lessons12-monitor
spec:
  selector:
    matchLabels:
      app: lessons12
  endpoints:
    - port: metrics
      path: /actuator/prometheus
      interval: 15s