{
 "title": "lessons12 dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": " 500 errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "group by (uri) (http_server_requests_seconds_count{status=~\"500\"})\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate (http_server_requests_seconds_count[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.5 percentil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(uri,le) (rate(http_server_requests_seconds_bucket{}[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.95 percentil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(uri,le) (rate(http_server_requests_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "0.99 percentil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(uri,le) (rate(http_server_requests_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "max percetil",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "histogram_quantile(1, sum by(uri,le) (rate(http_server_requests_seconds_bucket[1m])))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}