server:
  port: 8000
spring:
  datasource:
    url: jdbc:postgresql://psql-postgresql:5432/user_db
#    url: jdbc:postgresql://127.0.0.1:17789/user_db
    driver-class-name: org.postgresql.Driver
    username: user_pg
    password: pass_pg
  sql:
    init:
      mode: always

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"